In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import quandl as q

In [15]:
pd.read_csv(r"C:\Users\harshtiwari1711\Downloads\EOD-MCD.csv")

,Date,Open,High,Low,Close,Volume,Dividend,Split,Adj_Open,Adj_High,Adj_Low,Adj_Close,Adj_Volume
0,2017-12-28,173.260,173.55,172.620,173.10,1800068.0,0.0,1.0,161.897781,162.168763,161.299752,161.748274,1800068.0
1,2017-12-27,171.330,172.74,170.845,172.67,1596817.0,0.0,1.0,160.094349,161.411882,159.641154,161.346473,1596817.0
2,2017-12-26,171.090,171.64,170.820,171.29,1280227.0,0.0,1.0,159.870088,160.384019,159.617794,160.056972,1280227.0
3,2017-12-22,171.375,172.04,170.550,171.42,3234143.0,0.0,1.0,160.136398,160.757788,159.365500,160.178447,3234143.0
4,2017-12-21,172.680,172.75,171.670,171.85,2341676.0,0.0,1.0,161.355817,161.421226,160.412052,160.580248,2341676.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085,2013-09-09,96.220,96.79,96.210,96.45,3525200.0,0.0,1.0,78.828051,79.295023,78.819859,79.016478,3525200.0
1086,2013-09-06,95.870,96.75,95.250,96.26,4485800.0,0.0,1.0,78.541315,79.262253,78.033381,78.860821,4485800.0
1087,2013-09-05,95.330,96.46,95.080,95.66,4275300.0,0.0,1.0,78.098921,79.024671,77.894109,78.369272,4275300.0
1088,2013-09-04,94.500,95.36,94.340,95.16,2898800.0,0.0,1.0,77.418945,78.123498,77.287865,77.959648,2898800.0
1089,2013-09-03,95.100,95.28,94.120,94.52,3672100.0,0.0,1.0,77.910494,78.057958,77.107630,77.435330,3672100.0